### ISSUE TITLE
Exception during git pull update /  NoSuchFileException

### ISSUE THREAD

**Issue by ahus1** [docToolchain/diagrams.net-intellij-plugin#246]
I've seen an exception being reported, which might have been an concurrency issue. This should be handled more gracefully.

```
java.nio.file.NoSuchFileException: /home/aschwart/redhat/workspace/keycloak-benchmark/doc/resilience/modules/ROOT/images/site-record.png
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
at java.base/java.nio.file.Files.newInputStream(Files.java:160)
at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getInputStream(LocalFileSystemBase.java:470)
at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getInputStream(PersistentFSImpl.java:720)
at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getInputStream(VirtualFileImpl.java:108)
at de.docs_as_co.intellij.plugin.drawio.DiagramsFileUtil$Companion.isDiagramsFile(DiagramsFileUtil.kt:64)
at de.docs_as_co.intellij.plugin.drawio.icons.DiagramsEditorIconProvider.getIcon(DiagramsEditorIconProvider.kt:15)
at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
at com.intellij.util.IconUtil.getProviderIcon(IconUtil.kt:226)
at com.intellij.util.IconUtil.computeFileIconImpl(IconUtil.kt:167)
```

**Comment by ahus1** [comment]
fixed in next release
