### ISSUE TITLE
Deprecated ActionUpdateThread.OLD_EDT in future Jetbrains IDEs 

### ISSUE THREAD

**Issue by rob-mason** [docToolchain/diagrams.net-intellij-plugin#297]
Jetbrains Rider (as of 2024.1) is now reporting the following warning/error:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'de.docs_as_co.intellij.plugin.drawio.actions.OpenDevtoolsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: de.docs_as_co.intellij.plugin.diagramsnet]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by ahus1** [comment]
Thank you for letting me know. This will be fixed in the next version of the plugin. I'll update this issue once it is avialable.

**Comment by ahus1** [comment]
There is now pre-release v0.2.5 which includes a fix. Please give it a try if it fixes your problem.

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.
